### PR TITLE
Work on supporting Python 3.11

### LINKED ISSUE #27: Py 3.11: AttributeError: module 'inspect' has no attribute 'getargspec'
Running the tests with Plone 6.0 on Python 3.11 fails:

```
File "/Users/maurits/shared-eggs/cp311/plone.memoize-2.1.1-py3.11.egg/plone/memoize/request.rst", line 40, in request.rst
Failed example:
    cached_increment(A(1))
Exception raised:
    Traceback (most recent call last):
      File "/Users/maurits/.pyenv/versions/3.11.0rc2/lib/python3.11/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest request.rst[10]>", line 1, in <module>
        cached_increment(A(1))
      File "/Users/maurits/shared-eggs/cp311/plone.memoize-2.1.1-py3.11.egg/plone/memoize/volatile.py", line 71, in replacement
        cache = get_cache(fun, *args, **kwargs)
      File "/Users/maurits/shared-eggs/cp311/plone.memoize-2.1.1-py3.11.egg/plone/memoize/request.py", line 56, in _store_in_annotation
        spec = inspect.getargspec(fun)
    AttributeError: module 'inspect' has no attribute 'getargspec'
```

### PR DESCRIPTION
**Pull request by davisagli**
Working to fix #27, but may need more work on updating the CI

### CODE REVIEW

**Comment by davisagli** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — APPROVED** [review]
LGTM, and tests pass locally. Thanks!

I would also be okay with dropping Python 2.7 and 3.7 and make this Plone 6 only. But the package does not change often, so having only one branch to maintain for 5.2 and 6.0 is good as well. And the PR works, so we can leave it.

The PR jobs on Jenkins fail due to a Chrome/Chromedriver incompatibility. I have opened https://github.com/plone/jenkins.plone.org/issues/316 for that.
PR can be merged once the jobs are green.

**Comment by mauritsvanrees** [comment]
Should work now:

@jenkins-plone-org please run jobs
